 class Solution {
         public int numIslands(char[][] grid) {
                  Queue<int[]> que = new LinkedList<>();
                           int res = 0;
                                    for (int i = 0; i < grid.length; i++) {
                                                 for (int j = 0; j < grid[0].length; j++) {
                                                                  if (grid[i][j] == '1') {
                                                                                       que.offer(new int[]{i, j});
                                                                                                            grid[i][j] = '0';
                                                                                                                                 res += 1;
                                                                                                                                                      bfs(que, grid);
                                                                                                                                                                       }
                                                                                                                                                                                    }
                                                                                                                                                                                             }
                                                                                                                                                                                                      return res;
                                                                                                                                                                                                           }
                                                                                                                                                                                                            
                                                                                                                                                                                                                 void bfs(Queue<int[]> que, char[][] grid) {
                                                                                                                                                                                                                          int[] dr = {1, 0, -1, 0};
                                                                                                                                                                                                                                   int[] dc = {0, 1, 0, -1};
                                                                                                                                                                                                                                            while (!que.isEmpty()) {
                                                                                                                                                                                                                                                         int[] pos = que.poll();
                                                                                                                                                                                                                                                                      int r = pos[0];
                                                                                                                                                                                                                                                                                   int c = pos[1];
                                                                                                                                                                                                                                                                                                for (int i = 0; i < 4; i++) {
                                                                                                                                                                                                                                                                                                                 int nr = r + dr[i];
                                                                                                                                                                                                                                                                                                                                  int nc = c + dc[i];
                                                                                                                                                                                                                                                                                                                                                   if (nr < 0 || nr >= grid.length || nc < 0 || nc >= grid[0].length || grid[nr][nc] == '0') continue;
                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                     que.offer(new int[]{nr, nc});
                                                                                                                                                                                                                                                                                                                                                                                      grid[nr][nc] = '0';
                                                                                                                                                                                                                                                                                                                                                                                                   }
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                  }

 