 
  class Solution {
       public int ladderLength(String beginWord, String endWord, List<String> wordList) {
                Set<String> visited = new HashSet<>();
                         Queue<String> que = new LinkedList<>();
                                  que.offer(beginWord);
                                           visited.add(beginWord);
                                            
                                                     int count = 0;
                                                      
                                                               while (!que.isEmpty()) {
                                                                            int size = que.size();
                                                                                         count += 1;
                                                                                          
                                                                                                       for (int k = 0; k < size; k++) {
                                                                                                                        String top = que.poll();
                                                                                                                                         if (Objects.equals(top, endWord)) return count;
                                                                                                                                                          for (String word : wordList) {
                                                                                                                                                                               if (visited.contains(word)) continue;
                                                                                                                                                                                                    int diff = 0;
                                                                                                                                                                                                                         char[] currentWord = top.toCharArray();
                                                                                                                                                                                                                                              char[] targetWord = word.toCharArray();
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                                    for (int i = 0; i < currentWord.length; i++) {
                                                                                                                                                                                                                                                                                             if (currentWord[i] != targetWord[i]) {
                                                                                                                                                                                                                                                                                                                          diff += 1;
                                                                                                                                                                                                                                                                                                                                                       if (diff > 1) break;
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                          if (diff == 1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                   visited.add(word);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            que.offer(word);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        