 class Solution {
         List<List<String>> res = new ArrayList<>();
          
               public List<List<String>> solveNQueens(int n) {
                        backtrack(n, 0, new boolean[n], new boolean[n][n]);
                                 return res;
                                      }
                                       
                                            void backtrack(int n, int depth, boolean[] visit, boolean[][] board) {
                                                     if (depth >= n) {
                                                                  List<String> cur = new ArrayList<>();
                                                                               for (int i = 0; i < n; i++) {
                                                                                                StringBuilder str = new StringBuilder();
                                                                                                 
                                                                                                                  for (int j = 0; j < n; j++) {
                                                                                                                                       if (board[i][j]) str.append("Q");
                                                                                                                                                            else str.append(".");
                                                                                                                                                                             }
                                                                                                                                                                                              cur.add(str.toString());
                                                                                                                                                                                                           }
                                                                                                                                                                                                                        res.add(cur);
                                                                                                                                                                                                                                     return;
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                               
                                                                                                                                                                                                                                                        for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                     if (visit[i]) continue;
                                                                                                                                                                                                                                                                                  boolean check = false;
                                                                                                                                                                                                                                                                                               for (int j = 1; depth - j >= 0 && i - j >= 0; j++) {
                                                                                                                                                                                                                                                                                                                if (board[depth - j][i - j]) {
                                                                                                                                                                                                                                                                                                                                     check = true;
                                                                                                                                                                                                                                                                                                                                                          break;
                                                                                                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                     if (check) continue;
                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                   for (int j = 1; depth - j >= 0 && i + j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    if (board[depth - j][i + j]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                         check = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         if (check) continue;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        visit[i] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     board[depth][i] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  backtrack(n, depth + 1, visit, board);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               visit[i] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            board[depth][i] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           }

 