 class Solution {
           List<List<String>> res = new ArrayList<>();
                boolean[] cols;  // 열 체크
                     boolean[] diag1; // ↘ 대각선 (row - col)
                          boolean[] diag2; // ↙ 대각선 (row + col)
                           
                                public List<List<String>> solveNQueens(int n) {
                                         cols = new boolean[n];
                                                  diag1 = new boolean[2*n];
                                                           diag2 = new boolean[2*n];
                                                            
                                                                     backtrack(n, 0, new boolean[n][n]);
                                                                              return res;
                                                                                   }
                                                                                    
                                                                                         void backtrack(int n, int depth, boolean[][] board) {
                                                                                                  if (depth >= n) {
                                                                                                               List<String> cur = new ArrayList<>();
                                                                                                                            for (int i = 0; i < n; i++) {
                                                                                                                                             StringBuilder str = new StringBuilder();
                                                                                                                                              
                                                                                                                                                               for (int j = 0; j < n; j++) {
                                                                                                                                                                                    if (board[i][j]) str.append("Q");
                                                                                                                                                                                                         else str.append(".");
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                           cur.add(str.toString());
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                     res.add(cur);
                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                           }
                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                     for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                                                                  int d1 = depth - i + (n - 1); // ↘
                                                                                                                                                                                                                                                                                                                               int d2 = depth + i;           // ↙
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                             // 유망성 검사: 열이나 대각선에 이미 퀸이 있다면 건너뜀
                                                                                                                                                                                                                                                                                                                                                          if (cols[i] || diag1[d1] || diag2[d2]) continue;
                                                                                                                                                                                                                                                                                                                                                                       cols[i] = true;
                                                                                                                                                                                                                                                                                                                                                                                    diag1[d1] = true;
                                                                                                                                                                                                                                                                                                                                                                                                 diag2[d2] = true;
                                                                                                                                                                                                                                                                                                                                                                                                              board[depth][i] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                           backtrack(n, depth + 1, board);
                                                                                                                                                                                                                                                                                                                                                                                                                                        cols[i] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                     diag1[d1] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  diag2[d2] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                               board[depth][i] = false;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }

 