 class Solution {
         public String longestPalindrome(String s) {
                  if (s.isEmpty() || s.length() == 1) return s;
                   
                            int resLen = 0;
                                     String res = "";
                                              for (int center = 0; center < s.length(); center++) {
                                               
                                                            if (resLen < 1) {
                                                                             resLen = 1;
                                                                                              res = s.substring(center, center + 1);
                                                                                                           }
                                                                                                                        int left = center - 1;
                                                                                                                                     int right = center + 1;
                                                                                                                                      
                                                                                                                                                   while (left >= 0 && right < s.length()) {
                                                                                                                                                                    if (s.charAt(left) == s.charAt(right)) {
                                                                                                                                                                                         if (resLen < (right - left + 1)) {
                                                                                                                                                                                                                  resLen = right - left + 1;
                                                                                                                                                                                                                                           res = s.substring(left, right + 1);
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                     left--;
                                                                                                                                                                                                                                                                                                          right++;
                                                                                                                                                                                                                                                                                                                           } else break;
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                           for (int i = 0; i < s.length() - 1; i++) {
                                                                                                                                                                                                                                                                                                                                                                        int leftCenter = i;
                                                                                                                                                                                                                                                                                                                                                                                     int rightCenter = i + 1;
                                                                                                                                                                                                                                                                                                                                                                                                  if (s.charAt(leftCenter) != s.charAt(rightCenter)) continue;
                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                if (resLen < 2) {
                                                                                                                                                                                                                                                                                                                                                                                                                                 resLen = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                  res = s.substring(leftCenter, rightCenter + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                               }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int left = leftCenter - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         int right = rightCenter + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       while (left >= 0 && right < s.length()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (s.charAt(left) == s.charAt(right)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             if (resLen < (right - left + 1)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      resLen = right - left + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               res = s.substring(left, right + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         left--;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              right++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               } else break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return res;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       }

 